name: build-test

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Alpine Linux for armhf (target arch)
      id: alpine-target
      uses: jirutka/setup-alpine@v1
      with:
        arch: armhf
        branch: edge
        packages: >
          dbus-dev
          dbus-static
          mesa-gles
          libxkbcommon-dev
          wayland-dev
          libdrm
          mesa-gbm
          libinput
          eudev-dev
          elogind-dev
          wayland-protocols
          libx11-dev
        shell-name: alpine.sh

    - name: Create Build Environment
      shell: alpine.sh {0}
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Configure CMake to build libflutter_elinux.so
      shell: alpine.sh {0}
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_ELINUX_SO=ON -DBACKEND_TYPE=WAYLAND ..

    - name: Build libflutter_elinux.so
      working-directory: ${{github.workspace}}/build
      shell: alpine.sh {0}
      run: cmake --build . --config $BUILD_TYPE

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{github.workspace}}/build/libflutter_exlinux.so
